basePath: /shumingyu
definitions:
  shuming.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  shuming.UserResponse:
    properties:
      data:
        type: string
      msg:
        type: string
      record:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: 127.0.0.1:6620
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 書銘的API
  version: "1.0"
paths:
  /shumingyu/alluser:
    get:
      consumes:
      - application/json
      description: 回傳所有User的資料 跟 筆數
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 取得User資料
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: 增加User的資料
      parameters:
      - description: 帳號
        in: body
        name: account
        required: true
        schema:
          type: string
      - description: 使用者名稱
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 增加User
      tags:
      - Users
  /shumingyu/disabled:
    post:
      consumes:
      - application/json
      description: 修改User的狀態
      parameters:
      - description: 帳號
        in: body
        name: account
        required: true
        schema:
          type: string
      - description: 使用者名稱
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 使用者狀態(disabled/enabled)
        in: body
        name: status
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 修改User
      tags:
      - Users
  /shumingyu/example:
    get:
      consumes:
      - application/json
      description: 給書銘測試
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 測試
      tags:
      - Users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
