basePath: /shumingyu
definitions:
  shuming.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  shuming.UserResponse:
    properties:
      data:
        type: string
      errmsg:
        type: string
      msg:
        type: string
      record:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: 127.0.0.1:6620
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 書銘的API
  version: "1.0"
paths:
  /shumingyu/getoneproduct:
    post:
      consumes:
      - application/json
      description: 取得單一商品
      parameters:
      - description: 商品ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 取得單一商品
      tags:
      - Product
  /shumingyu/login:
    post:
      consumes:
      - application/json
      description: 登入功能
      parameters:
      - description: 使用者名稱
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: 密碼
        in: body
        name: Password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 登入功能
      tags:
      - Login
  /shumingyu/order:
    delete:
      consumes:
      - application/json
      description: 刪掉訂單
      parameters:
      - description: 訂單ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 刪掉訂單
      tags:
      - Order
    get:
      consumes:
      - application/json
      description: 回傳所有訂單的資料 跟 筆數
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 取得訂單清單
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: 新增訂單
      parameters:
      - description: 用戶名稱
        in: body
        name: User
        required: true
        schema:
          type: string
      - description: 訂單總金額
        in: body
        name: Total_amount
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 新增訂單
      tags:
      - Order
    put:
      consumes:
      - application/json
      description: 更新訂單
      parameters:
      - description: 用戶資訊
        in: body
        name: User_id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 更新訂單
      tags:
      - Order
  /shumingyu/product:
    delete:
      consumes:
      - application/json
      description: 刪掉商品資料
      parameters:
      - description: 商品ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 刪掉商品資料
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: 回傳所有商品的資料 跟 筆數
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 取得商品資料
      tags:
      - Product
    post:
      consumes:
      - application/json
      description: 新增商品資料
      parameters:
      - description: 商品名稱
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: 描述
        in: body
        name: Description
        schema:
          type: string
      - description: 價格
        in: body
        name: Price
        schema:
          type: string
      - description: 折扣 例如10代表打9折
        in: body
        name: Discount
        schema:
          type: string
      - description: 庫存
        in: body
        name: Stock
        schema:
          type: string
      - description: 庫存單位
        in: body
        name: SKU
        schema:
          type: string
      - description: 圖片
        in: body
        name: ImageURL
        schema:
          type: string
      - description: 商品分類
        in: body
        name: Category
        schema:
          type: string
      - description: 商品啟用(0/1)
        in: body
        name: Enabled
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 新增商品資料
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: 更新商品資料
      parameters:
      - description: 商品ID
        in: body
        name: Id
        required: true
        schema:
          type: string
      - description: 商品名稱
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: 描述
        in: body
        name: Description
        schema:
          type: string
      - description: 價格
        in: body
        name: Price
        schema:
          type: string
      - description: 折扣 例如10代表打9折
        in: body
        name: Discount
        schema:
          type: string
      - description: 庫存
        in: body
        name: Stock
        schema:
          type: string
      - description: 庫存單位
        in: body
        name: SKU
        schema:
          type: string
      - description: 圖片
        in: body
        name: ImageURL
        schema:
          type: string
      - description: 商品分類
        in: body
        name: Category
        schema:
          type: string
      - description: 商品啟用(0/1)
        in: body
        name: Enabled
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 更新商品資料
      tags:
      - Product
  /shumingyu/productcategory:
    get:
      consumes:
      - application/json
      description: 回傳商品的所有種類
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 取得商品種類
      tags:
      - Product
  /shumingyu/report:
    get:
      consumes:
      - application/json
      description: 回傳統計值
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 取得報表
      tags:
      - Report
  /shumingyu/user:
    delete:
      consumes:
      - application/json
      description: 刪掉User的資料
      parameters:
      - description: 使用者ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 刪掉User
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: 回傳所有User的資料 跟 筆數
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 取得User資料
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: 增加User的資料
      parameters:
      - description: 使用者名稱
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: 電子信箱
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: 密碼
        in: body
        name: Password
        required: true
        schema:
          type: string
      - description: 住址
        in: body
        name: Address
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 增加User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: 更新User的資料
      parameters:
      - description: 使用者ID
        in: body
        name: Id
        required: true
        schema:
          type: string
      - description: 使用者名稱
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: 電子信箱
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: 密碼
        in: body
        name: Password
        required: true
        schema:
          type: string
      - description: 住址
        in: body
        name: Address
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/shuming.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/shuming.ErrorResponse'
      summary: 更新User
      tags:
      - Users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
